// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: shapeapi/shapeapi.proto

package shapeapi_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShapeAPI_GenerateShape_FullMethodName = "/shapeapi.ShapeAPI/GenerateShape"
)

// ShapeAPIClient is the client API for ShapeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShapeAPIClient interface {
	GenerateShape(ctx context.Context, in *ToolShape, opts ...grpc.CallOption) (*ToolShape, error)
}

type shapeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewShapeAPIClient(cc grpc.ClientConnInterface) ShapeAPIClient {
	return &shapeAPIClient{cc}
}

func (c *shapeAPIClient) GenerateShape(ctx context.Context, in *ToolShape, opts ...grpc.CallOption) (*ToolShape, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolShape)
	err := c.cc.Invoke(ctx, ShapeAPI_GenerateShape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShapeAPIServer is the server API for ShapeAPI service.
// All implementations must embed UnimplementedShapeAPIServer
// for forward compatibility.
type ShapeAPIServer interface {
	GenerateShape(context.Context, *ToolShape) (*ToolShape, error)
	mustEmbedUnimplementedShapeAPIServer()
}

// UnimplementedShapeAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShapeAPIServer struct{}

func (UnimplementedShapeAPIServer) GenerateShape(context.Context, *ToolShape) (*ToolShape, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShape not implemented")
}
func (UnimplementedShapeAPIServer) mustEmbedUnimplementedShapeAPIServer() {}
func (UnimplementedShapeAPIServer) testEmbeddedByValue()                  {}

// UnsafeShapeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShapeAPIServer will
// result in compilation errors.
type UnsafeShapeAPIServer interface {
	mustEmbedUnimplementedShapeAPIServer()
}

func RegisterShapeAPIServer(s grpc.ServiceRegistrar, srv ShapeAPIServer) {
	// If the following call pancis, it indicates UnimplementedShapeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShapeAPI_ServiceDesc, srv)
}

func _ShapeAPI_GenerateShape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolShape)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShapeAPIServer).GenerateShape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShapeAPI_GenerateShape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShapeAPIServer).GenerateShape(ctx, req.(*ToolShape))
	}
	return interceptor(ctx, in, info, handler)
}

// ShapeAPI_ServiceDesc is the grpc.ServiceDesc for ShapeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShapeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shapeapi.ShapeAPI",
	HandlerType: (*ShapeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateShape",
			Handler:    _ShapeAPI_GenerateShape_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shapeapi/shapeapi.proto",
}
