// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: shapeapi/shapeapi.proto

package shapeapi_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	X             *float64               `protobuf:"fixed64,2,opt,name=x,proto3,oneof" json:"x,omitempty"`
	Y             *float64               `protobuf:"fixed64,3,opt,name=y,proto3,oneof" json:"y,omitempty"`
	Circle        *bool                  `protobuf:"varint,4,opt,name=circle,proto3,oneof" json:"circle,omitempty"`
	Opacity       *float64               `protobuf:"fixed64,5,opt,name=opacity,proto3,oneof" json:"opacity,omitempty"`
	Rgb           *string                `protobuf:"bytes,6,opt,name=rgb,proto3,oneof" json:"rgb,omitempty"`
	Rotation      *float64               `protobuf:"fixed64,7,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"`
	Scale         *float64               `protobuf:"fixed64,8,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	Sides         *int32                 `protobuf:"varint,9,opt,name=sides,proto3,oneof" json:"sides,omitempty"`
	Star          *bool                  `protobuf:"varint,10,opt,name=star,proto3,oneof" json:"star,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolShape) Reset() {
	*x = ToolShape{}
	mi := &file_shapeapi_shapeapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolShape) ProtoMessage() {}

func (x *ToolShape) ProtoReflect() protoreflect.Message {
	mi := &file_shapeapi_shapeapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolShape.ProtoReflect.Descriptor instead.
func (*ToolShape) Descriptor() ([]byte, []int) {
	return file_shapeapi_shapeapi_proto_rawDescGZIP(), []int{0}
}

func (x *ToolShape) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ToolShape) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *ToolShape) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *ToolShape) GetCircle() bool {
	if x != nil && x.Circle != nil {
		return *x.Circle
	}
	return false
}

func (x *ToolShape) GetOpacity() float64 {
	if x != nil && x.Opacity != nil {
		return *x.Opacity
	}
	return 0
}

func (x *ToolShape) GetRgb() string {
	if x != nil && x.Rgb != nil {
		return *x.Rgb
	}
	return ""
}

func (x *ToolShape) GetRotation() float64 {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return 0
}

func (x *ToolShape) GetScale() float64 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

func (x *ToolShape) GetSides() int32 {
	if x != nil && x.Sides != nil {
		return *x.Sides
	}
	return 0
}

func (x *ToolShape) GetStar() bool {
	if x != nil && x.Star != nil {
		return *x.Star
	}
	return false
}

var File_shapeapi_shapeapi_proto protoreflect.FileDescriptor

const file_shapeapi_shapeapi_proto_rawDesc = "" +
	"\n" +
	"\x17shapeapi/shapeapi.proto\x12\bshapeapi\"\xe5\x02\n" +
	"\tToolShape\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x11\n" +
	"\x01x\x18\x02 \x01(\x01H\x01R\x01x\x88\x01\x01\x12\x11\n" +
	"\x01y\x18\x03 \x01(\x01H\x02R\x01y\x88\x01\x01\x12\x1b\n" +
	"\x06circle\x18\x04 \x01(\bH\x03R\x06circle\x88\x01\x01\x12\x1d\n" +
	"\aopacity\x18\x05 \x01(\x01H\x04R\aopacity\x88\x01\x01\x12\x15\n" +
	"\x03rgb\x18\x06 \x01(\tH\x05R\x03rgb\x88\x01\x01\x12\x1f\n" +
	"\brotation\x18\a \x01(\x01H\x06R\brotation\x88\x01\x01\x12\x19\n" +
	"\x05scale\x18\b \x01(\x01H\aR\x05scale\x88\x01\x01\x12\x19\n" +
	"\x05sides\x18\t \x01(\x05H\bR\x05sides\x88\x01\x01\x12\x17\n" +
	"\x04star\x18\n" +
	" \x01(\bH\tR\x04star\x88\x01\x01B\x05\n" +
	"\x03_idB\x04\n" +
	"\x02_xB\x04\n" +
	"\x02_yB\t\n" +
	"\a_circleB\n" +
	"\n" +
	"\b_opacityB\x06\n" +
	"\x04_rgbB\v\n" +
	"\t_rotationB\b\n" +
	"\x06_scaleB\b\n" +
	"\x06_sidesB\a\n" +
	"\x05_star2E\n" +
	"\bShapeAPI\x129\n" +
	"\rGenerateShape\x12\x13.shapeapi.ToolShape\x1a\x13.shapeapi.ToolShapeB\x1aZ\x18/shapeapi_pb;shapeapi_pbb\x06proto3"

var (
	file_shapeapi_shapeapi_proto_rawDescOnce sync.Once
	file_shapeapi_shapeapi_proto_rawDescData []byte
)

func file_shapeapi_shapeapi_proto_rawDescGZIP() []byte {
	file_shapeapi_shapeapi_proto_rawDescOnce.Do(func() {
		file_shapeapi_shapeapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shapeapi_shapeapi_proto_rawDesc), len(file_shapeapi_shapeapi_proto_rawDesc)))
	})
	return file_shapeapi_shapeapi_proto_rawDescData
}

var file_shapeapi_shapeapi_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shapeapi_shapeapi_proto_goTypes = []any{
	(*ToolShape)(nil), // 0: shapeapi.ToolShape
}
var file_shapeapi_shapeapi_proto_depIdxs = []int32{
	0, // 0: shapeapi.ShapeAPI.GenerateShape:input_type -> shapeapi.ToolShape
	0, // 1: shapeapi.ShapeAPI.GenerateShape:output_type -> shapeapi.ToolShape
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shapeapi_shapeapi_proto_init() }
func file_shapeapi_shapeapi_proto_init() {
	if File_shapeapi_shapeapi_proto != nil {
		return
	}
	file_shapeapi_shapeapi_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shapeapi_shapeapi_proto_rawDesc), len(file_shapeapi_shapeapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shapeapi_shapeapi_proto_goTypes,
		DependencyIndexes: file_shapeapi_shapeapi_proto_depIdxs,
		MessageInfos:      file_shapeapi_shapeapi_proto_msgTypes,
	}.Build()
	File_shapeapi_shapeapi_proto = out.File
	file_shapeapi_shapeapi_proto_goTypes = nil
	file_shapeapi_shapeapi_proto_depIdxs = nil
}
