global using System;
global using Npgsql;
global using Serilog;
global using System.Text;
global using System.Linq;
global using Serilog.Core;
global using OpenTelemetry;
global using System.Fabric;
global using Serilog.Events;
global using System.Threading;
global using System.Diagnostics;
global using KusDepot.CatalogDb;
global using OpenTelemetry.Trace;
global using KusDepot.Data.Models;
global using System.Globalization;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Exporter;
global using System.Threading.Tasks;
global using OpenTelemetry.Resources;
global using System.Fabric.Description;
global using static System.Environment;
global using System.Collections.Generic;
global using System.Diagnostics.Tracing;
global using Serilog.Sinks.OpenTelemetry;
global using System.Security.Cryptography;
global using Microsoft.ServiceFabric.Data;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.ServiceFabric.Actors;
global using System.Runtime.CompilerServices;
global using Microsoft.Extensions.Configuration;
global using Microsoft.EntityFrameworkCore.Design;
global using static KusDepot.Data.CatalogDBStrings;
global using Microsoft.ServiceFabric.Actors.Runtime;
global using static KusDepot.Data.CatalogDBSettings;
global using static System.Globalization.CultureInfo;
global using Microsoft.EntityFrameworkCore.Migrations;
global using DiagnosticActivity = System.Diagnostics.Activity;