// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shapeapi/shapeapi.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Shapeapi {

  /// <summary>Holder for reflection information generated from shapeapi/shapeapi.proto</summary>
  public static partial class ShapeapiReflection {

    #region Descriptor
    /// <summary>File descriptor for shapeapi/shapeapi.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShapeapiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdzaGFwZWFwaS9zaGFwZWFwaS5wcm90bxIIc2hhcGVhcGkipwIKCVRvb2xT",
            "aGFwZRIPCgJpZBgBIAEoCUgAiAEBEg4KAXgYAiABKAFIAYgBARIOCgF5GAMg",
            "ASgBSAKIAQESEwoGY2lyY2xlGAQgASgISAOIAQESFAoHb3BhY2l0eRgFIAEo",
            "AUgEiAEBEhAKA3JnYhgGIAEoCUgFiAEBEhUKCHJvdGF0aW9uGAcgASgBSAaI",
            "AQESEgoFc2NhbGUYCCABKAFIB4gBARISCgVzaWRlcxgJIAEoBUgIiAEBEhEK",
            "BHN0YXIYCiABKAhICYgBAUIFCgNfaWRCBAoCX3hCBAoCX3lCCQoHX2NpcmNs",
            "ZUIKCghfb3BhY2l0eUIGCgRfcmdiQgsKCV9yb3RhdGlvbkIICgZfc2NhbGVC",
            "CAoGX3NpZGVzQgcKBV9zdGFyMkUKCFNoYXBlQVBJEjkKDUdlbmVyYXRlU2hh",
            "cGUSEy5zaGFwZWFwaS5Ub29sU2hhcGUaEy5zaGFwZWFwaS5Ub29sU2hhcGVC",
            "GloYL3NoYXBlYXBpX3BiO3NoYXBlYXBpX3BiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Shapeapi.ToolShape), global::Shapeapi.ToolShape.Parser, new[]{ "Id", "X", "Y", "Circle", "Opacity", "Rgb", "Rotation", "Scale", "Sides", "Star" }, new[]{ "Id", "X", "Y", "Circle", "Opacity", "Rgb", "Rotation", "Scale", "Sides", "Star" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ToolShape : pb::IMessage<ToolShape>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ToolShape> _parser = new pb::MessageParser<ToolShape>(() => new ToolShape());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ToolShape> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shapeapi.ShapeapiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ToolShape() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ToolShape(ToolShape other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      x_ = other.x_;
      y_ = other.y_;
      circle_ = other.circle_;
      opacity_ = other.opacity_;
      rgb_ = other.rgb_;
      rotation_ = other.rotation_;
      scale_ = other.scale_;
      sides_ = other.sides_;
      star_ = other.star_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ToolShape Clone() {
      return new ToolShape(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static string IdDefaultValue = "";

    private string id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_ ?? IdDefaultValue; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return id_ != null; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      id_ = null;
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 2;
    private readonly static double XDefaultValue = 0D;

    private double x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double X {
      get { if ((_hasBits0 & 1) != 0) { return x_; } else { return XDefaultValue; } }
      set {
        _hasBits0 |= 1;
        x_ = value;
      }
    }
    /// <summary>Gets whether the "x" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasX {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "x" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearX() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 3;
    private readonly static double YDefaultValue = 0D;

    private double y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Y {
      get { if ((_hasBits0 & 2) != 0) { return y_; } else { return YDefaultValue; } }
      set {
        _hasBits0 |= 2;
        y_ = value;
      }
    }
    /// <summary>Gets whether the "y" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasY {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "y" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearY() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "circle" field.</summary>
    public const int CircleFieldNumber = 4;
    private readonly static bool CircleDefaultValue = false;

    private bool circle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Circle {
      get { if ((_hasBits0 & 4) != 0) { return circle_; } else { return CircleDefaultValue; } }
      set {
        _hasBits0 |= 4;
        circle_ = value;
      }
    }
    /// <summary>Gets whether the "circle" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCircle {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "circle" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCircle() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "opacity" field.</summary>
    public const int OpacityFieldNumber = 5;
    private readonly static double OpacityDefaultValue = 0D;

    private double opacity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Opacity {
      get { if ((_hasBits0 & 8) != 0) { return opacity_; } else { return OpacityDefaultValue; } }
      set {
        _hasBits0 |= 8;
        opacity_ = value;
      }
    }
    /// <summary>Gets whether the "opacity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOpacity {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "opacity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOpacity() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "rgb" field.</summary>
    public const int RgbFieldNumber = 6;
    private readonly static string RgbDefaultValue = "";

    private string rgb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Rgb {
      get { return rgb_ ?? RgbDefaultValue; }
      set {
        rgb_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "rgb" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRgb {
      get { return rgb_ != null; }
    }
    /// <summary>Clears the value of the "rgb" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRgb() {
      rgb_ = null;
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 7;
    private readonly static double RotationDefaultValue = 0D;

    private double rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Rotation {
      get { if ((_hasBits0 & 16) != 0) { return rotation_; } else { return RotationDefaultValue; } }
      set {
        _hasBits0 |= 16;
        rotation_ = value;
      }
    }
    /// <summary>Gets whether the "rotation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRotation {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "rotation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRotation() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "scale" field.</summary>
    public const int ScaleFieldNumber = 8;
    private readonly static double ScaleDefaultValue = 0D;

    private double scale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Scale {
      get { if ((_hasBits0 & 32) != 0) { return scale_; } else { return ScaleDefaultValue; } }
      set {
        _hasBits0 |= 32;
        scale_ = value;
      }
    }
    /// <summary>Gets whether the "scale" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScale {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "scale" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScale() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "sides" field.</summary>
    public const int SidesFieldNumber = 9;
    private readonly static int SidesDefaultValue = 0;

    private int sides_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sides {
      get { if ((_hasBits0 & 64) != 0) { return sides_; } else { return SidesDefaultValue; } }
      set {
        _hasBits0 |= 64;
        sides_ = value;
      }
    }
    /// <summary>Gets whether the "sides" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSides {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "sides" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSides() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "star" field.</summary>
    public const int StarFieldNumber = 10;
    private readonly static bool StarDefaultValue = false;

    private bool star_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Star {
      get { if ((_hasBits0 & 128) != 0) { return star_; } else { return StarDefaultValue; } }
      set {
        _hasBits0 |= 128;
        star_ = value;
      }
    }
    /// <summary>Gets whether the "star" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStar {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "star" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStar() {
      _hasBits0 &= ~128;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ToolShape);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ToolShape other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Y, other.Y)) return false;
      if (Circle != other.Circle) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Opacity, other.Opacity)) return false;
      if (Rgb != other.Rgb) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Rotation, other.Rotation)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Scale, other.Scale)) return false;
      if (Sides != other.Sides) return false;
      if (Star != other.Star) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasX) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(X);
      if (HasY) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Y);
      if (HasCircle) hash ^= Circle.GetHashCode();
      if (HasOpacity) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Opacity);
      if (HasRgb) hash ^= Rgb.GetHashCode();
      if (HasRotation) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Rotation);
      if (HasScale) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Scale);
      if (HasSides) hash ^= Sides.GetHashCode();
      if (HasStar) hash ^= Star.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (HasX) {
        output.WriteRawTag(17);
        output.WriteDouble(X);
      }
      if (HasY) {
        output.WriteRawTag(25);
        output.WriteDouble(Y);
      }
      if (HasCircle) {
        output.WriteRawTag(32);
        output.WriteBool(Circle);
      }
      if (HasOpacity) {
        output.WriteRawTag(41);
        output.WriteDouble(Opacity);
      }
      if (HasRgb) {
        output.WriteRawTag(50);
        output.WriteString(Rgb);
      }
      if (HasRotation) {
        output.WriteRawTag(57);
        output.WriteDouble(Rotation);
      }
      if (HasScale) {
        output.WriteRawTag(65);
        output.WriteDouble(Scale);
      }
      if (HasSides) {
        output.WriteRawTag(72);
        output.WriteInt32(Sides);
      }
      if (HasStar) {
        output.WriteRawTag(80);
        output.WriteBool(Star);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (HasX) {
        output.WriteRawTag(17);
        output.WriteDouble(X);
      }
      if (HasY) {
        output.WriteRawTag(25);
        output.WriteDouble(Y);
      }
      if (HasCircle) {
        output.WriteRawTag(32);
        output.WriteBool(Circle);
      }
      if (HasOpacity) {
        output.WriteRawTag(41);
        output.WriteDouble(Opacity);
      }
      if (HasRgb) {
        output.WriteRawTag(50);
        output.WriteString(Rgb);
      }
      if (HasRotation) {
        output.WriteRawTag(57);
        output.WriteDouble(Rotation);
      }
      if (HasScale) {
        output.WriteRawTag(65);
        output.WriteDouble(Scale);
      }
      if (HasSides) {
        output.WriteRawTag(72);
        output.WriteInt32(Sides);
      }
      if (HasStar) {
        output.WriteRawTag(80);
        output.WriteBool(Star);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (HasX) {
        size += 1 + 8;
      }
      if (HasY) {
        size += 1 + 8;
      }
      if (HasCircle) {
        size += 1 + 1;
      }
      if (HasOpacity) {
        size += 1 + 8;
      }
      if (HasRgb) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Rgb);
      }
      if (HasRotation) {
        size += 1 + 8;
      }
      if (HasScale) {
        size += 1 + 8;
      }
      if (HasSides) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sides);
      }
      if (HasStar) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ToolShape other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasX) {
        X = other.X;
      }
      if (other.HasY) {
        Y = other.Y;
      }
      if (other.HasCircle) {
        Circle = other.Circle;
      }
      if (other.HasOpacity) {
        Opacity = other.Opacity;
      }
      if (other.HasRgb) {
        Rgb = other.Rgb;
      }
      if (other.HasRotation) {
        Rotation = other.Rotation;
      }
      if (other.HasScale) {
        Scale = other.Scale;
      }
      if (other.HasSides) {
        Sides = other.Sides;
      }
      if (other.HasStar) {
        Star = other.Star;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 17: {
            X = input.ReadDouble();
            break;
          }
          case 25: {
            Y = input.ReadDouble();
            break;
          }
          case 32: {
            Circle = input.ReadBool();
            break;
          }
          case 41: {
            Opacity = input.ReadDouble();
            break;
          }
          case 50: {
            Rgb = input.ReadString();
            break;
          }
          case 57: {
            Rotation = input.ReadDouble();
            break;
          }
          case 65: {
            Scale = input.ReadDouble();
            break;
          }
          case 72: {
            Sides = input.ReadInt32();
            break;
          }
          case 80: {
            Star = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 17: {
            X = input.ReadDouble();
            break;
          }
          case 25: {
            Y = input.ReadDouble();
            break;
          }
          case 32: {
            Circle = input.ReadBool();
            break;
          }
          case 41: {
            Opacity = input.ReadDouble();
            break;
          }
          case 50: {
            Rgb = input.ReadString();
            break;
          }
          case 57: {
            Rotation = input.ReadDouble();
            break;
          }
          case 65: {
            Scale = input.ReadDouble();
            break;
          }
          case 72: {
            Sides = input.ReadInt32();
            break;
          }
          case 80: {
            Star = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
