global using System;
global using CoreWCF;
global using KusDepot;
global using System.IO;
global using System.Xml;
global using System.Linq;
global using System.Fabric;
global using Serilog.Events;
global using CoreWCF.Security;
global using System.Threading;
global using System.Text.Json;
global using CoreWCF.Channels;
global using System.Diagnostics;
global using CoreWCF.Description;
global using System.Net.Security;
global using System.Globalization;
global using CoreWCF.Configuration;
global using System.Threading.Tasks;
global using static KusDepot.Utility;
global using static System.Environment;
global using System.Collections.Generic;
global using System.IdentityModel.Tokens;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using CoreWCF.IdentityModel.Selectors;
global using Microsoft.Extensions.Configuration;
global using static System.Globalization.CultureInfo;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.ServiceFabric.Services.Runtime;
global using static KusDepot.ToolFabric.ToolFabricStrings;
global using System.Security.Cryptography.X509Certificates;
global using Microsoft.ServiceFabric.Services.Communication.Runtime;