global using KusDepot;
global using KusDepot.Builders;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using System;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net.Security;
global using System.Security.Cryptography.X509Certificates;
global using System.Text.Json;
global using System.Threading.Tasks;
global using Weblzr.Components;
global using static System.Environment;
global using static System.Globalization.CultureInfo;
global using static Weblzr.Strings;