global using System;
global using Serilog;
global using RestSharp;
global using Grpc.Core;
global using System.Linq;
global using System.Text;
global using Grpc.Net.Client;
global using System.Collections;
global using System.Globalization;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using System.Security.Cryptography;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.SignalR;
global using System.Text.RegularExpressions;
global using System.Runtime.CompilerServices;
global using Microsoft.Extensions.Configuration;
global using static KusDepot.Reacts.ReactorStrings;
global using static KusDepot.Reacts.StringSanitizer;
global using Microsoft.Extensions.DependencyInjection;
global using static KusDepot.Reacts.ToolShapeGenerator;
global using static KusDepot.Reacts.ToolShapeGeneratorStrings;