global using KusDepot;
global using KusDepot.Builders;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.ResponseCompression;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog;
global using System;
global using System.Globalization;
global using System.IO.Compression;
global using System.Threading.Tasks;
global using static KusDepotSolutions.WebStrings;