global using KusDepot;
global using Serilog;
global using System;
global using System.Globalization;
global using System.IO;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using ToolShapeServices;
global using static ToolShapeServices.ToolShapeGenerator;