global using System;
global using Autofac;
global using CoreWCF;
global using System.IO;
global using System.Xml;
global using System.Linq;
global using System.Data;
global using System.Text;
global using FluentValidation;
global using System.Threading;
global using System.Reflection;
global using System.Globalization;
global using System.IO.Compression;
global using System.Threading.Tasks;
global using static KusDepot.Settings;
global using System.Collections.Generic;
global using System.Runtime.Serialization;
global using System.Collections.Immutable;
global using System.Security.Cryptography;
global using Microsoft.Extensions.Hosting;
global using System.Security.AccessControl;
global using static KusDepot.SyncException;
global using System.Diagnostics.CodeAnalysis;
global using static System.Threading.Monitor;
global using System.Security.Cryptography.X509Certificates;