global using Azure.Storage;
global using Azure.Storage.Blobs;
global using Azure.Storage.Blobs.Models;
global using KusDepot.Exceptions;
global using KusDepot.Data.Transfer;
global using KusDepot.Logging;
global using KusDepot.Serialization;
global using KusDepot.Serialization.Buffers;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.JsonWebTokens;
global using Orleans;
global using Serilog;
global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Runtime.InteropServices;
global using System.Runtime.Serialization;
global using System.Text.Json.Serialization;
global using Microsoft.Win32.SafeHandles;
global using System.Buffers;
global using System.Security.Cryptography;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Xml;
global using Windows.Win32;
global using Windows.Win32.Foundation;
global using static KusDepot.Constants.BinarySizes;
global using static KusDepot.Data.Services.DataTransfer.DataTransferConstants;
global using static KusDepot.Settings;
global using static KusDepot.Strings.ExceptionStrings;
global using static KusDepot.Utilities.Utility;
global using static System.Buffers.Binary.BinaryPrimitives;
global using static System.Globalization.CultureInfo;