//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolServiceExam
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandDetails", Namespace="KusDepot")]
    public partial class CommandDetails : object
    {
        
        private System.Collections.Generic.Dictionary<string, object> ArgumentsField;
        
        private string HandleField;
        
        private System.Nullable<System.Guid> IDField;
        
        private ToolServiceExam.CommandWorkflow WorkflowField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, object> Arguments
        {
            get
            {
                return this.ArgumentsField;
            }
            set
            {
                this.ArgumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Handle
        {
            get
            {
                return this.HandleField;
            }
            set
            {
                this.HandleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ToolServiceExam.CommandWorkflow Workflow
        {
            get
            {
                return this.WorkflowField;
            }
            set
            {
                this.WorkflowField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandWorkflow", Namespace="KusDepot")]
    public partial class CommandWorkflow : object
    {
        
        private System.Collections.Generic.Dictionary<string, string> EventLogField;
        
        private System.Collections.Generic.Dictionary<int, string> SequenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> EventLog
        {
            get
            {
                return this.EventLogField;
            }
            set
            {
                this.EventLogField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<int, string> Sequence
        {
            get
            {
                return this.SequenceField;
            }
            set
            {
                this.SequenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuidReferenceItem", Namespace="KusDepot")]
    public partial class GuidReferenceItem : ToolServiceExam.DataItem
    {
        
        private System.Nullable<System.Guid> ContentField;
        
        private ToolServiceExam.GuidReferenceItem NextField;
        
        private ToolServiceExam.GuidReferenceItem PreviousField;
        
        private System.Collections.Generic.List<ToolServiceExam.GuidReferenceItem> UndirectedLinksField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ToolServiceExam.GuidReferenceItem Next
        {
            get
            {
                return this.NextField;
            }
            set
            {
                this.NextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ToolServiceExam.GuidReferenceItem Previous
        {
            get
            {
                return this.PreviousField;
            }
            set
            {
                this.PreviousField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<ToolServiceExam.GuidReferenceItem> UndirectedLinks
        {
            get
            {
                return this.UndirectedLinksField;
            }
            set
            {
                this.UndirectedLinksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Common", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MetaBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.KeySet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.TextItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CodeItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.BinaryItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MSBuildItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.GenericItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataSetItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MultiMediaItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.GuidReferenceItem))]
    public partial class Common : object
    {
        
        private System.Nullable<System.Guid> IDField;
        
        private bool LockedField;
        
        private bool MyNoExceptionsField;
        
        private System.Collections.Generic.List<byte[]> SecretsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Locked
        {
            get
            {
                return this.LockedField;
            }
            set
            {
                this.LockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool MyNoExceptions
        {
            get
            {
                return this.MyNoExceptionsField;
            }
            set
            {
                this.MyNoExceptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<byte[]> Secrets
        {
            get
            {
                return this.SecretsField;
            }
            set
            {
                this.SecretsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaBase", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.KeySet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.TextItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CodeItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.BinaryItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MSBuildItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.GenericItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataSetItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MultiMediaItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.GuidReferenceItem))]
    public partial class MetaBase : ToolServiceExam.Common
    {
        
        private string ApplicationField;
        
        private System.Version ApplicationVersionField;
        
        private System.Nullable<System.DateTimeOffset> BornOnField;
        
        private string DistinguishedNameField;
        
        private string DomainIDField;
        
        private System.Collections.Generic.Dictionary<string, object> ExtensionField;
        
        private string FILEField;
        
        private System.Collections.Generic.Dictionary<string, ToolServiceExam.GuidReferenceItem> LinksField;
        
        private System.Nullable<System.DateTimeOffset> ModifiedField;
        
        private string NameField;
        
        private System.Collections.Generic.List<string> NotesField;
        
        private string SecurityDescriptorField;
        
        private System.Version ServiceVersionField;
        
        private System.Collections.Generic.List<string> TagsField;
        
        private System.Version VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Version ApplicationVersion
        {
            get
            {
                return this.ApplicationVersionField;
            }
            set
            {
                this.ApplicationVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTimeOffset> BornOn
        {
            get
            {
                return this.BornOnField;
            }
            set
            {
                this.BornOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DistinguishedName
        {
            get
            {
                return this.DistinguishedNameField;
            }
            set
            {
                this.DistinguishedNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DomainID
        {
            get
            {
                return this.DomainIDField;
            }
            set
            {
                this.DomainIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, object> Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FILE
        {
            get
            {
                return this.FILEField;
            }
            set
            {
                this.FILEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, ToolServiceExam.GuidReferenceItem> Links
        {
            get
            {
                return this.LinksField;
            }
            set
            {
                this.LinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTimeOffset> Modified
        {
            get
            {
                return this.ModifiedField;
            }
            set
            {
                this.ModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<string> Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SecurityDescriptor
        {
            get
            {
                return this.SecurityDescriptorField;
            }
            set
            {
                this.SecurityDescriptorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Version ServiceVersion
        {
            get
            {
                return this.ServiceVersionField;
            }
            set
            {
                this.ServiceVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<string> Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Version Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataItem", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.KeySet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.TextItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CodeItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.BinaryItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MSBuildItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.GenericItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataSetItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MultiMediaItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.GuidReferenceItem))]
    public partial class DataItem : ToolServiceExam.MetaBase
    {
        
        private bool ContentStreamedField;
        
        private ToolServiceExam.DataEncryptInfo DataEncryptInfoField;
        
        private bool DataEncryptedField;
        
        private bool DataMaskedField;
        
        private byte[] EncryptedDataField;
        
        private System.Collections.Generic.Dictionary<string, byte[]> SecureHashesField;
        
        private System.Collections.Generic.Dictionary<string, byte[]> SecureSignaturesField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ContentStreamed
        {
            get
            {
                return this.ContentStreamedField;
            }
            set
            {
                this.ContentStreamedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ToolServiceExam.DataEncryptInfo DataEncryptInfo
        {
            get
            {
                return this.DataEncryptInfoField;
            }
            set
            {
                this.DataEncryptInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool DataEncrypted
        {
            get
            {
                return this.DataEncryptedField;
            }
            set
            {
                this.DataEncryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool DataMasked
        {
            get
            {
                return this.DataMaskedField;
            }
            set
            {
                this.DataMaskedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] EncryptedData
        {
            get
            {
                return this.EncryptedDataField;
            }
            set
            {
                this.EncryptedDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, byte[]> SecureHashes
        {
            get
            {
                return this.SecureHashesField;
            }
            set
            {
                this.SecureHashesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, byte[]> SecureSignatures
        {
            get
            {
                return this.SecureSignaturesField;
            }
            set
            {
                this.SecureSignaturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeySet", Namespace="KusDepot")]
    public partial class KeySet : ToolServiceExam.DataItem
    {
        
        private System.Collections.Generic.Dictionary<string, ToolServiceExam.SecurityKey> AllKeysField;
        
        private byte[] OwnerSecretField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, ToolServiceExam.SecurityKey> AllKeys
        {
            get
            {
                return this.AllKeysField;
            }
            set
            {
                this.AllKeysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] OwnerSecret
        {
            get
            {
                return this.OwnerSecretField;
            }
            set
            {
                this.OwnerSecretField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextItem", Namespace="KusDepot")]
    public partial class TextItem : ToolServiceExam.DataItem
    {
        
        private string ContentField;
        
        private string LanguageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeItem", Namespace="KusDepot")]
    public partial class CodeItem : ToolServiceExam.DataItem
    {
        
        private string ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BinaryItem", Namespace="KusDepot")]
    public partial class BinaryItem : ToolServiceExam.DataItem
    {
        
        private System.Collections.Generic.List<System.Tuple<string, string, string>> CommandsField;
        
        private byte[] ContentField;
        
        private System.Collections.Generic.List<System.Tuple<string, string>> ServicesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<System.Tuple<string, string, string>> Commands
        {
            get
            {
                return this.CommandsField;
            }
            set
            {
                this.CommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<System.Tuple<string, string>> Services
        {
            get
            {
                return this.ServicesField;
            }
            set
            {
                this.ServicesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSBuildItem", Namespace="KusDepot")]
    public partial class MSBuildItem : ToolServiceExam.DataItem
    {
        
        private string ContentField;
        
        private System.Collections.Generic.List<ToolServiceExam.DataItem> RequirementsField;
        
        private System.Collections.Generic.Dictionary<int, ToolServiceExam.MSBuildItem> SequenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<ToolServiceExam.DataItem> Requirements
        {
            get
            {
                return this.RequirementsField;
            }
            set
            {
                this.RequirementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<int, ToolServiceExam.MSBuildItem> Sequence
        {
            get
            {
                return this.SequenceField;
            }
            set
            {
                this.SequenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericItem", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Stack<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Queue<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<int, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<uint>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<char>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<sbyte>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<short>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ushort>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<long>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ulong>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<float>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<double>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<decimal>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Guid>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<byte[]>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, ToolServiceExam.GuidReferenceItem>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, ToolServiceExam.SecurityKey>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<int, ToolServiceExam.MSBuildItem>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Nullable<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, ToolServiceExam.KusDepotCab>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CommandDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CommandWorkflow))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ToolServiceExam.DataItem>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MetaBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.Common))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.GuidReferenceItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ToolServiceExam.GuidReferenceItem>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.KeySet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.SecurityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.HostKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.AccessKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.OwnerKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ManagementKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MyHostKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ClientKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ManagerKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ServiceKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CommandKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ExecutiveKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ServiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.AccessRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.StandardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ManagementRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.TextItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CodeItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.BinaryItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MSBuildItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.KusDepotCab))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.Descriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataSetItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MultiMediaItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.DataEncryptInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Version))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.DateTimeOffset))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<char>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<byte>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<sbyte>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<short>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<ushort>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<uint>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<long>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<ulong>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<float>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<double>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<decimal>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<System.Guid>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Tuple<string, string, string>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Tuple<string, string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Tuple<string, string>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Tuple<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.BigInteger))]
    public partial class GenericItem : ToolServiceExam.DataItem
    {
        
        private System.Collections.Generic.List<object> ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<object> Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetItem", Namespace="KusDepot")]
    public partial class DataSetItem : ToolServiceExam.DataItem
    {
        
        private System.Collections.Generic.List<ToolServiceExam.DataItem> ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<ToolServiceExam.DataItem> Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiMediaItem", Namespace="KusDepot")]
    public partial class MultiMediaItem : ToolServiceExam.DataItem
    {
        
        private System.Collections.Generic.List<string> ArtistsField;
        
        private System.Nullable<double> BitrateField;
        
        private byte[] ContentField;
        
        private System.Nullable<decimal> DurationField;
        
        private System.Nullable<float> FramerateField;
        
        private string LanguageField;
        
        private string TitleField;
        
        private bool UseSourceStreamField;
        
        private System.Nullable<int> YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<string> Artists
        {
            get
            {
                return this.ArtistsField;
            }
            set
            {
                this.ArtistsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Bitrate
        {
            get
            {
                return this.BitrateField;
            }
            set
            {
                this.BitrateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> Framerate
        {
            get
            {
                return this.FramerateField;
            }
            set
            {
                this.FramerateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UseSourceStream
        {
            get
            {
                return this.UseSourceStreamField;
            }
            set
            {
                this.UseSourceStreamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataEncryptInfo", Namespace="KusDepot")]
    public partial class DataEncryptInfo : object
    {
        
        private System.Nullable<System.Guid> ManagementKeyIDField;
        
        private string PublicKeyField;
        
        private string SerialField;
        
        private string ThumbPrintField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> ManagementKeyID
        {
            get
            {
                return this.ManagementKeyIDField;
            }
            set
            {
                this.ManagementKeyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PublicKey
        {
            get
            {
                return this.PublicKeyField;
            }
            set
            {
                this.PublicKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ThumbPrint
        {
            get
            {
                return this.ThumbPrintField;
            }
            set
            {
                this.ThumbPrintField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityKey", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.AccessKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.HostKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MyHostKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ClientKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ServiceKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CommandKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ExecutiveKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ManagementKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.OwnerKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ManagerKey))]
    public partial class SecurityKey : object
    {
        
        private System.Nullable<System.Guid> IDField;
        
        private byte[] KeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessKey", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.HostKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.MyHostKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ClientKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ServiceKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.CommandKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ExecutiveKey))]
    public partial class AccessKey : ToolServiceExam.SecurityKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HostKey", Namespace="KusDepot")]
    public partial class HostKey : ToolServiceExam.AccessKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyHostKey", Namespace="KusDepot")]
    public partial class MyHostKey : ToolServiceExam.AccessKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientKey", Namespace="KusDepot")]
    public partial class ClientKey : ToolServiceExam.AccessKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceKey", Namespace="KusDepot")]
    public partial class ServiceKey : ToolServiceExam.AccessKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandKey", Namespace="KusDepot")]
    public partial class CommandKey : ToolServiceExam.AccessKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutiveKey", Namespace="KusDepot")]
    public partial class ExecutiveKey : ToolServiceExam.AccessKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagementKey", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.OwnerKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ManagerKey))]
    public partial class ManagementKey : ToolServiceExam.SecurityKey
    {
        
        private string ThumbprintField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Thumbprint
        {
            get
            {
                return this.ThumbprintField;
            }
            set
            {
                this.ThumbprintField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OwnerKey", Namespace="KusDepot")]
    public partial class OwnerKey : ToolServiceExam.ManagementKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagerKey", Namespace="KusDepot")]
    public partial class ManagerKey : ToolServiceExam.ManagementKey
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KusDepotCab", Namespace="KusDepot")]
    public partial class KusDepotCab : object
    {
        
        private System.Collections.Generic.Dictionary<string, ToolServiceExam.KusDepotCab> CargoField;
        
        private string DataField;
        
        private System.Collections.Generic.Dictionary<string, string> ManifestField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, ToolServiceExam.KusDepotCab> Cargo
        {
            get
            {
                return this.CargoField;
            }
            set
            {
                this.CargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> Manifest
        {
            get
            {
                return this.ManifestField;
            }
            set
            {
                this.ManifestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequest", Namespace="KusDepot")]
    public partial class ServiceRequest : ToolServiceExam.AccessRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessRequest", Namespace="KusDepot")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.StandardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ManagementRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToolServiceExam.ServiceRequest))]
    public partial class AccessRequest : object
    {
        
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardRequest", Namespace="KusDepot")]
    public partial class StandardRequest : ToolServiceExam.AccessRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagementRequest", Namespace="KusDepot")]
    public partial class ManagementRequest : ToolServiceExam.AccessRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Descriptor", Namespace="KusDepot")]
    public partial class Descriptor : object
    {
        
        private string ApplicationField;
        
        private string ApplicationVersionField;
        
        private string ArtistField;
        
        private string BornOnField;
        
        private System.Collections.Generic.List<System.Tuple<string, string, string>> CommandsField;
        
        private System.Nullable<bool> ContentStreamedField;
        
        private string DistinguishedNameField;
        
        private string FILEField;
        
        private System.Nullable<System.Guid> IDField;
        
        private bool LiveStreamField;
        
        private string ModifiedField;
        
        private string NameField;
        
        private System.Collections.Generic.List<string> NotesField;
        
        private string ObjectTypeField;
        
        private string ServiceVersionField;
        
        private System.Collections.Generic.List<System.Tuple<string, string>> ServicesField;
        
        private string SizeField;
        
        private System.Collections.Generic.List<string> TagsField;
        
        private string TitleField;
        
        private string TypeField;
        
        private string VersionField;
        
        private string YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ApplicationVersion
        {
            get
            {
                return this.ApplicationVersionField;
            }
            set
            {
                this.ApplicationVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Artist
        {
            get
            {
                return this.ArtistField;
            }
            set
            {
                this.ArtistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BornOn
        {
            get
            {
                return this.BornOnField;
            }
            set
            {
                this.BornOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<System.Tuple<string, string, string>> Commands
        {
            get
            {
                return this.CommandsField;
            }
            set
            {
                this.CommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> ContentStreamed
        {
            get
            {
                return this.ContentStreamedField;
            }
            set
            {
                this.ContentStreamedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DistinguishedName
        {
            get
            {
                return this.DistinguishedNameField;
            }
            set
            {
                this.DistinguishedNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FILE
        {
            get
            {
                return this.FILEField;
            }
            set
            {
                this.FILEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool LiveStream
        {
            get
            {
                return this.LiveStreamField;
            }
            set
            {
                this.LiveStreamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Modified
        {
            get
            {
                return this.ModifiedField;
            }
            set
            {
                this.ModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<string> Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ServiceVersion
        {
            get
            {
                return this.ServiceVersionField;
            }
            set
            {
                this.ServiceVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<System.Tuple<string, string>> Services
        {
            get
            {
                return this.ServicesField;
            }
            set
            {
                this.ServicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<string> Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BigInteger", Namespace="http://schemas.datacontract.org/2004/07/System.Numerics")]
    public partial struct BigInteger
    {
        
        private System.Collections.Generic.List<uint> _bitsField;
        
        private int _signField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<uint> _bits
        {
            get
            {
                return this._bitsField;
            }
            set
            {
                this._bitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _sign
        {
            get
            {
                return this._signField;
            }
            set
            {
                this._signField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="KusDepot", ConfigurationName="ToolServiceExam.IToolService")]
    public interface IToolService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="KusDepot/IToolService/ExecuteCommand", ReplyAction="KusDepot/IToolService/ExecuteCommandResponse")]
        System.Nullable<System.Guid> ExecuteCommand(ToolServiceExam.CommandDetails details, ToolServiceExam.AccessKey key);
        
        [System.ServiceModel.OperationContractAttribute(Action="KusDepot/IToolService/ExecuteCommandCab", ReplyAction="KusDepot/IToolService/ExecuteCommandCabResponse")]
        System.Nullable<System.Guid> ExecuteCommandCab(ToolServiceExam.KusDepotCab cab, ToolServiceExam.AccessKey key);
        
        [System.ServiceModel.OperationContractAttribute(Action="KusDepot/IToolService/GetOutput", ReplyAction="KusDepot/IToolService/GetOutputResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Stack<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Queue<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<int, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<uint>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<char>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<int>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<sbyte>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<short>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<ushort>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<ulong>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<float>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<double>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<decimal>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Guid>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, ToolServiceExam.GuidReferenceItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, ToolServiceExam.SecurityKey>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<int, ToolServiceExam.MSBuildItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Nullable<int>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, ToolServiceExam.KusDepotCab>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.CommandDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.CommandWorkflow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<ToolServiceExam.DataItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.DataItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.MetaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.Common))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.GuidReferenceItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<ToolServiceExam.GuidReferenceItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.KeySet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.SecurityKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.HostKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.AccessKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.OwnerKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.ManagementKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.MyHostKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.ClientKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.ManagerKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.ServiceKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.CommandKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.ExecutiveKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.ServiceRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.AccessRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.StandardRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.ManagementRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.TextItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.CodeItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.BinaryItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.MSBuildItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.GenericItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.KusDepotCab))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.Descriptor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.DataSetItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.MultiMediaItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.DataEncryptInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Version))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTimeOffset))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<char>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<int>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<byte>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<sbyte>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<short>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<ushort>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<uint>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<ulong>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<float>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<double>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<decimal>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<System.Guid>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Tuple<string, string, string>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Tuple<string, string>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ToolServiceExam.BigInteger))]
        object GetOutput(System.Nullable<System.Guid> id, ToolServiceExam.AccessKey key);
        
        [System.ServiceModel.OperationContractAttribute(Action="KusDepot/IToolService/RequestAccess", ReplyAction="KusDepot/IToolService/RequestAccessResponse")]
        ToolServiceExam.AccessKey RequestAccess(ToolServiceExam.AccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="KusDepot/IToolService/RevokeAccess", ReplyAction="KusDepot/IToolService/RevokeAccessResponse")]
        bool RevokeAccess(ToolServiceExam.AccessKey key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IToolServiceChannel : ToolServiceExam.IToolService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ToolServiceClient : System.ServiceModel.ClientBase<ToolServiceExam.IToolService>, ToolServiceExam.IToolService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ToolServiceClient() : 
                base(ToolServiceClient.GetDefaultBinding(), ToolServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ToolService_IToolService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ToolServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ToolServiceClient.GetBindingForEndpoint(endpointConfiguration), ToolServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ToolServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ToolServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ToolServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ToolServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ToolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Nullable<System.Guid> ExecuteCommand(ToolServiceExam.CommandDetails details, ToolServiceExam.AccessKey key)
        {
            return base.Channel.ExecuteCommand(details, key);
        }
        
        public System.Nullable<System.Guid> ExecuteCommandCab(ToolServiceExam.KusDepotCab cab, ToolServiceExam.AccessKey key)
        {
            return base.Channel.ExecuteCommandCab(cab, key);
        }
        
        public object GetOutput(System.Nullable<System.Guid> id, ToolServiceExam.AccessKey key)
        {
            return base.Channel.GetOutput(id, key);
        }
        
        public ToolServiceExam.AccessKey RequestAccess(ToolServiceExam.AccessRequest request)
        {
            return base.Channel.RequestAccess(request);
        }
        
        public bool RevokeAccess(ToolServiceExam.AccessKey key)
        {
            return base.Channel.RevokeAccess(key);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ToolService_IToolService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ToolService_IToolService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8086/ToolService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ToolServiceClient.GetBindingForEndpoint(EndpointConfiguration.ToolService_IToolService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ToolServiceClient.GetEndpointAddress(EndpointConfiguration.ToolService_IToolService);
        }
        
        public enum EndpointConfiguration
        {
            
            ToolService_IToolService,
        }
    }
}
