# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import shapeapi_pb2 as shapeapi__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shapeapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShapeAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateShape = channel.unary_unary(
                '/shapeapi.ShapeAPI/GenerateShape',
                request_serializer=shapeapi__pb2.ToolShape.SerializeToString,
                response_deserializer=shapeapi__pb2.ToolShape.FromString,
                _registered_method=True)


class ShapeAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateShape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShapeAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateShape': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateShape,
                    request_deserializer=shapeapi__pb2.ToolShape.FromString,
                    response_serializer=shapeapi__pb2.ToolShape.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shapeapi.ShapeAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shapeapi.ShapeAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShapeAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateShape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shapeapi.ShapeAPI/GenerateShape',
            shapeapi__pb2.ToolShape.SerializeToString,
            shapeapi__pb2.ToolShape.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
