# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shapeapi.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shapeapi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshapeapi.proto\x12\x08shapeapi\"\xa7\x02\n\tToolShape\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x01x\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x0e\n\x01y\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x13\n\x06\x63ircle\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x14\n\x07opacity\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x10\n\x03rgb\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x15\n\x08rotation\x18\x07 \x01(\x01H\x06\x88\x01\x01\x12\x12\n\x05scale\x18\x08 \x01(\x01H\x07\x88\x01\x01\x12\x12\n\x05sides\x18\t \x01(\x05H\x08\x88\x01\x01\x12\x11\n\x04star\x18\n \x01(\x08H\t\x88\x01\x01\x42\x05\n\x03_idB\x04\n\x02_xB\x04\n\x02_yB\t\n\x07_circleB\n\n\x08_opacityB\x06\n\x04_rgbB\x0b\n\t_rotationB\x08\n\x06_scaleB\x08\n\x06_sidesB\x07\n\x05_star2E\n\x08ShapeAPI\x12\x39\n\rGenerateShape\x12\x13.shapeapi.ToolShape\x1a\x13.shapeapi.ToolShapeB\x1aZ\x18/shapeapi_pb;shapeapi_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shapeapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030/shapeapi_pb;shapeapi_pb'
  _globals['_TOOLSHAPE']._serialized_start=29
  _globals['_TOOLSHAPE']._serialized_end=324
  _globals['_SHAPEAPI']._serialized_start=326
  _globals['_SHAPEAPI']._serialized_end=395
# @@protoc_insertion_point(module_scope)
