global using KusDepot.Builders;
global using KusDepot.Security;
global using KusDepot.Data.Services.Configuration;
global using Microsoft.AspNetCore.Authentication.Certificate;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Http.Features;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.OpenApi;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.OpenApi.Models;
global using Microsoft.ServiceFabric.Actors.Client;
global using Microsoft.ServiceFabric.Services.Communication.Runtime;
global using Microsoft.ServiceFabric.Services.Runtime;
global using OpenTelemetry.Exporter;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
global using Scalar.AspNetCore;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using Serilog.Sinks.OpenTelemetry;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.Tracing;
global using System.Fabric;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net.Security;
global using System.Runtime.CompilerServices;
global using System.Security.Claims;
global using System.Security.Cryptography.X509Certificates;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using static KusDepot.Data.CatalogStrings;
global using KusDepot.Data.Models;
global using static KusDepot.Data.Utility.TraceUtility;
global using static System.Environment;
global using static System.StringComparison;
global using DiagnosticActivity = System.Diagnostics.Activity;