global using System;
global using Serilog;
global using KusDepot;
global using System.Threading;
global using System.Globalization;
global using System.Threading.Tasks;
global using ModelContextProtocol.Server;
global using Microsoft.AspNetCore.Hosting;
global using ModelContextProtocol.Protocol;