global using KusDepot.Data.Models;
global using KusDepot.Data.Services.DataTransfer;
global using KusDepot.Data.Transfer;
global using KusDepot.Exceptions;
global using KusDepot.Logging;
global using KusDepot.Services;
global using KusDepot.Serialization;
global using Microsoft.AspNetCore.SignalR.Client;
global using Microsoft.Extensions.Options;
global using RestSharp;
global using RestSharp.Authenticators;
global using System;
global using System.Buffers;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Security.Cryptography;
global using System.Security.Cryptography.X509Certificates;
global using System.Text;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using static KusDepot.Constants.BinarySizes;
global using static KusDepot.Data.Clients.CatalogClientStrings;
global using static KusDepot.Data.Clients.DataControlClientStrings;
global using static KusDepot.Data.Services.DataTransfer.DataTransferConstants;
global using static KusDepot.Settings;
global using static KusDepot.Utilities.Utility;