Write-Host "$(([DateTimeOffset]::Now).ToString()) - KusDepot Clean Start"

Remove-Item -Recurse "$env:KusDepotSolution\AD\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\AD\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Blob\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Blob\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Catalog\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Catalog\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\CatalogDB\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\CatalogDB\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\CmdletPS\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\CmdletPS\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Command\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Command\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\CoreCache\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\CoreCache\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DaprActors\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DaprActors\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DaprSidecar\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DaprSidecar\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DataConfigs\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DataConfigs\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DataControl\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DataControl\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DepotClients\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DepotClients\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Act\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Act\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Act\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.AIO\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.AIO\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.CMD\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.CMD\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Dap\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Dap\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Dap\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Data\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Data\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Data\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exam\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exam\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exams\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exams\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Fabrics\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Fabrics\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Objects\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Objects\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Onlines\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Onlines\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Orleans\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Orleans\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Orleans\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Packages\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Packages\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Services\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Services\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.SourceGen\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.SourceGen\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolService\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolService\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceExam\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceExam\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceFabric\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceFabric\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceFabric\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceHost\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceHost\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolServiceHost\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolWorkflow\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolWorkflow\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolWorkflow\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Weblzr\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Weblzr\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Weblzr\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KustoEmulator\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KustoEmulator\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labnativemix\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labnativemix\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboperator\Laboperator.AppHost\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboperator\Laboperator.AppHost\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboratory\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboratory\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labspace\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labspace\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labvoid\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labvoid\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\LabX02\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\LabX02\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Metal\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Metal\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Mgmt\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Mgmt\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactF\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactF\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactG\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactG\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactJ\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactJ\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactJ\target" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactL\ReactL.AppHost\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactL\ReactL.AppHost\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\node_modules" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\target" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\.venv" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\reactp\__pycache__" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactR\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactR\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactR\target" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Reacts\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Reacts\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Reacts\node_modules" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Secure\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Secure\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Services\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Services\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolActor\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolActor\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolFabric\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolFabric\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolGrains\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolGrains\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Toolmixer\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Toolmixer\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolWork\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolWork\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\UnoTool\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\UnoTool\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Weblzr\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Weblzr\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\WinViewsRT\WinViewsRT\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\WinViewsRT\WinViewsRT\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\WinViewsRT\WinViewsRTX\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\WinViewsRT\WinViewsRTX\obj" -Force

Write-Host "$(([DateTimeOffset]::Now).ToString()) - KusDepot Clean Complete"