Write-Host "$(([DateTimeOffset]::Now).ToString()) - KusDepot Clean Start"

Remove-Item -Recurse "$env:KusDepotSolution\DaprSidecar\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DaprSidecar\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DataServices\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DataServices\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DepotClients\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\DepotClients\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.AIO\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.AIO\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ASPR\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ASPR\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.BLDRS\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.BLDRS\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.CMD\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.CMD\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Dap\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Dap\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Dap\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exam\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exam\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exams\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Exams\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Objects\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Objects\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Packages\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Packages\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Performance\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Performance\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Services\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.Services\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.SourceGen\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.SourceGen\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolManifests\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolManifests\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolWorkflow\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolWorkflow\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepot.ToolWorkflow\pkg" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\App\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\App\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\Catalog\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\Catalog\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\DataControl\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\DataControl\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\Services\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\Services\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\Shared\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotDataPod\Shared\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotSolutions\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotSolutions\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KusDepotSolutions\node_modules" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KustoEmulator\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\KustoEmulator\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboperator\Laboperator.AppHost\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboperator\Laboperator.AppHost\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboratory\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Laboratory\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labspace\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labspace\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labvoid\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Labvoid\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\LabX02\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\LabX02\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\LabX08\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\LabX08\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactF\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactF\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactG\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactG\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactJ\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactJ\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactJ\target" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactL\ReactL.AppHost\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactL\ReactL.AppHost\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\node_modules" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactN\target" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\.venv" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactP\reactp\__pycache__" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactR\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactR\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ReactR\target" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Reacts\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Reacts\obj" -Force
Remove-Item -Recurse "$env:KusDepotSolution\Reacts\node_modules" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolWork\bin" -Force
Remove-Item -Recurse "$env:KusDepotSolution\ToolWork\obj" -Force

Write-Host "$(([DateTimeOffset]::Now).ToString()) - KusDepot Clean Complete"