global using System;
global using Serilog;
global using System.Linq;
global using Serilog.Core;
global using OpenTelemetry;
global using System.Fabric;
global using Serilog.Events;
global using System.Threading;
global using System.Diagnostics;
global using OpenTelemetry.Trace;
global using System.Globalization;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Exporter;
global using System.Threading.Tasks;
global using OpenTelemetry.Resources;
global using System.Fabric.Description;
global using static System.Environment;
global using System.Collections.Generic;
global using System.Diagnostics.Tracing;
global using Serilog.Sinks.OpenTelemetry;
global using Microsoft.ServiceFabric.Data;
global using Microsoft.ServiceFabric.Actors;
global using System.Runtime.CompilerServices;
global using static KusDepot.Data.TraceUtility;
global using Microsoft.Extensions.Configuration;
global using Microsoft.ServiceFabric.Actors.Client;
global using Microsoft.ServiceFabric.Actors.Runtime;
global using static System.Globalization.CultureInfo;
global using static KusDepot.Data.DataConfigsStrings;
global using static KusDepot.Data.DataConfigsSettings;
global using DiagnosticActivity = System.Diagnostics.Activity;