global using KusDepot.Data.Configuration.Security;
global using KusDepot.Data.Services.Configuration;
global using Microsoft.Extensions.Configuration;
global using Microsoft.IdentityModel.JsonWebTokens;
global using Microsoft.IdentityModel.Protocols;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.ServiceFabric.Actors;
global using Microsoft.ServiceFabric.Actors.Client;
global using Microsoft.ServiceFabric.Actors.Runtime;
global using Microsoft.ServiceFabric.Data;
global using OpenTelemetry;
global using OpenTelemetry.Exporter;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using Serilog.Sinks.OpenTelemetry;
global using System;
global using System.Linq;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.Tracing;
global using System.Runtime.CompilerServices;
global using System.Threading;
global using System.Threading.Tasks;
global using static KusDepot.Data.DataConfigsSettings;
global using static KusDepot.Data.DataConfigsStrings;
global using static KusDepot.Data.Utility.TraceUtility;
global using static KusDepot.Utilities.Utility;
global using static System.Environment;
global using static System.Globalization.CultureInfo;
global using DiagnosticActivity = System.Diagnostics.Activity;