global using System;
global using Serilog;
global using System.Linq;
global using OpenTelemetry;
global using System.Threading;
global using System.Diagnostics;
global using OpenTelemetry.Trace;
global using System.Threading.Tasks;
global using static System.Environment;
global using Microsoft.ServiceFabric.Actors;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.IdentityModel.Protocols;
global using static KusDepot.Data.TraceUtility;
global using static KusDepot.Data.SecureStrings;
global using Microsoft.Extensions.Configuration;
global using Microsoft.IdentityModel.JsonWebTokens;
global using Microsoft.ServiceFabric.Actors.Runtime;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
global using DiagnosticActivity = System.Diagnostics.Activity;