// <auto-generated />
using System;
using KusDepot.CatalogDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogDB.CatalogDBContextMigrations
{
    [DbContext(typeof(CatalogDBContext))]
    partial class CatalogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KusDepot.CatalogDb.Command", b =>
                {
                    b.Property<Guid>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("text");

                    b.Property<string>("BornOn")
                        .HasColumnType("text");

                    b.Property<string>("CommandHandle")
                        .HasColumnType("text");

                    b.Property<string>("CommandSpecifications")
                        .HasColumnType("text");

                    b.Property<string>("CommandType")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<bool?>("ContentStreamed")
                        .HasColumnType("boolean");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<Guid?>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Modified")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text");

                    b.Property<string>("ServiceVersion")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("PrimaryKey");

                    b.HasIndex("ID");

                    b.ToTable("Commands", (string)null);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Element", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("text");

                    b.Property<string>("BornOn")
                        .HasColumnType("text");

                    b.Property<bool?>("ContentStreamed")
                        .HasColumnType("boolean");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("Modified")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text");

                    b.Property<string>("ServiceVersion")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Elements", (string)null);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.MultiMedia", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("BornOn")
                        .HasColumnType("text");

                    b.Property<bool?>("ContentStreamed")
                        .HasColumnType("boolean");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("Modified")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MediaLibrary", (string)null);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Note", b =>
                {
                    b.Property<Guid>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PrimaryKey");

                    b.HasIndex("Value");

                    b.HasIndex("ID", "Value")
                        .IsUnique();

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Service", b =>
                {
                    b.Property<Guid>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("text");

                    b.Property<string>("BornOn")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<bool?>("ContentStreamed")
                        .HasColumnType("boolean");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<Guid?>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Modified")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text");

                    b.Property<string>("ServiceInterfaces")
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .HasColumnType("text");

                    b.Property<string>("ServiceVersion")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("PrimaryKey");

                    b.HasIndex("ID");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Tag", b =>
                {
                    b.Property<Guid>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PrimaryKey");

                    b.HasIndex("Value");

                    b.HasIndex("ID", "Value")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Command", b =>
                {
                    b.HasOne("KusDepot.CatalogDb.Element", null)
                        .WithMany()
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.MultiMedia", b =>
                {
                    b.HasOne("KusDepot.CatalogDb.Element", null)
                        .WithOne()
                        .HasForeignKey("KusDepot.CatalogDb.MultiMedia", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Note", b =>
                {
                    b.HasOne("KusDepot.CatalogDb.Element", null)
                        .WithMany()
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Service", b =>
                {
                    b.HasOne("KusDepot.CatalogDb.Element", null)
                        .WithMany()
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KusDepot.CatalogDb.Tag", b =>
                {
                    b.HasOne("KusDepot.CatalogDb.Element", null)
                        .WithMany()
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
