global using System;
global using KusDepot;
global using System.Net;
global using Dapr.Workflow;
global using System.Fabric;
global using Serilog.Events;
global using System.Threading;
global using System.Text.Json;
global using System.Diagnostics;
global using KusDepot.DaprActors;
global using System.Globalization;
global using System.Threading.Tasks;
global using static System.Environment;
global using System.Collections.Generic;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.Hosting;
global using Microsoft.AspNetCore.Builder;
global using static ToolWork.DaprWorkerStrings;
global using Microsoft.Extensions.Configuration;
global using static System.Globalization.CultureInfo;
global using Microsoft.ServiceFabric.Services.Runtime;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.ServiceFabric.Services.Communication.Runtime;