global using Dapr.Workflow;
global using KusDepot;
global using KusDepot.Builders;
global using KusDepot.Logging;
global using KusDepot.Security;
global using KusDepot.DaprActors;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.ServiceFabric.Services.Communication.Runtime;
global using Microsoft.ServiceFabric.Services.Runtime;
global using Serilog.Events;
global using System;
global using System.Collections.Generic;
global using System.Fabric;
global using System.Globalization;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using static KusDepot.Utilities.Utility;
global using static System.Environment;
global using static System.Globalization.CultureInfo;
global using static ToolWork.DaprWorkerStrings;