FROM mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
ENV DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://0.0.0.0:4317
ENV DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
ENV Dashboard__ApplicationName=KusDepot
EXPOSE 18888
EXPOSE 4317