global using KusDepot.Exceptions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.ServiceFabric.Actors;
global using Microsoft.ServiceFabric.Actors.Runtime;
global using OpenTelemetry;
global using OpenTelemetry.Exporter;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using Serilog.Sinks.OpenTelemetry;
global using StackExchange.Redis;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.Tracing;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Threading;
global using System.Threading.Tasks;
global using static KusDepot.Data.CoreCacheSettings;
global using static KusDepot.Data.CoreCacheStrings;
global using static KusDepot.Utilities.Utility;
global using static System.Environment;
global using static System.StringComparison;
global using DiagnosticActivity = System.Diagnostics.Activity;