global using Azure.Storage;
global using KusDepot;
global using KusDepot.Builders;
global using KusDepot.Data.Services.Configuration;
global using KusDepot.Exceptions;
global using KusDepot.Logging;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using Microsoft.IdentityModel.JsonWebTokens;
global using Microsoft.IdentityModel.Protocols;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
global using Microsoft.IdentityModel.Tokens;
global using OpenTelemetry;
global using OpenTelemetry.Exporter;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
global using Orleans;
global using Orleans.Configuration;
global using Orleans.Hosting;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using Serilog.Extensions.Logging;
global using Serilog.Sinks.OpenTelemetry;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.Tracing;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Runtime.CompilerServices;
global using System.Security.Cryptography;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using static KusDepot.Data.Utility.TraceUtility;
global using static KusDepot.Utilities.Utility;
global using static System.Environment;
global using DiagnosticActivity = System.Diagnostics.Activity;