namespace EntitySQLArk;

[PrimaryKey("ID")]
public partial class Note : ModelBase
{
    public override Guid? ID {get;set;}

    public String? Note0  {get;set;}
    public String? Note1  {get;set;}
    public String? Note2  {get;set;}
    public String? Note3  {get;set;}
    public String? Note4  {get;set;}
    public String? Note5  {get;set;}
    public String? Note6  {get;set;}
    public String? Note7  {get;set;}
    public String? Note8  {get;set;}
    public String? Note9  {get;set;}
    public String? Note10 {get;set;}
    public String? Note11 {get;set;}
    public String? Note12 {get;set;}
    public String? Note13 {get;set;}
    public String? Note14 {get;set;}
    public String? Note15 {get;set;}
    public String? Note16 {get;set;}
    public String? Note17 {get;set;}
    public String? Note18 {get;set;}
    public String? Note19 {get;set;}
    public String? Note20 {get;set;}
    public String? Note21 {get;set;}
    public String? Note22 {get;set;}
    public String? Note23 {get;set;}
    public String? Note24 {get;set;}
    public String? Note25 {get;set;}
    public String? Note26 {get;set;}
    public String? Note27 {get;set;}
    public String? Note28 {get;set;}
    public String? Note29 {get;set;}
    public String? Note30 {get;set;}
    public String? Note31 {get;set;}
    public String? Note32 {get;set;}
    public String? Note33 {get;set;}
    public String? Note34 {get;set;}
    public String? Note35 {get;set;}
    public String? Note36 {get;set;}
    public String? Note37 {get;set;}
    public String? Note38 {get;set;}
    public String? Note39 {get;set;}
    public String? Note40 {get;set;}
    public String? Note41 {get;set;}
    public String? Note42 {get;set;}
    public String? Note43 {get;set;}
    public String? Note44 {get;set;}
    public String? Note45 {get;set;}
    public String? Note46 {get;set;}
    public String? Note47 {get;set;}
    public String? Note48 {get;set;}
    public String? Note49 {get;set;}
    public String? Note50 {get;set;}
    public String? Note51 {get;set;}
    public String? Note52 {get;set;}
    public String? Note53 {get;set;}
    public String? Note54 {get;set;}
    public String? Note55 {get;set;}
    public String? Note56 {get;set;}
    public String? Note57 {get;set;}
    public String? Note58 {get;set;}
    public String? Note59 {get;set;}
    public String? Note60 {get;set;}
    public String? Note61 {get;set;}
    public String? Note62 {get;set;}
    public String? Note63 {get;set;}
    public String? Note64 {get;set;}
    public String? Note65 {get;set;}
    public String? Note66 {get;set;}
    public String? Note67 {get;set;}
    public String? Note68 {get;set;}
    public String? Note69 {get;set;}
    public String? Note70 {get;set;}
    public String? Note71 {get;set;}
    public String? Note72 {get;set;}
    public String? Note73 {get;set;}
    public String? Note74 {get;set;}
    public String? Note75 {get;set;}
    public String? Note76 {get;set;}
    public String? Note77 {get;set;}
    public String? Note78 {get;set;}
    public String? Note79 {get;set;}
    public String? Note80 {get;set;}
    public String? Note81 {get;set;}
    public String? Note82 {get;set;}
    public String? Note83 {get;set;}
    public String? Note84 {get;set;}
    public String? Note85 {get;set;}
    public String? Note86 {get;set;}
    public String? Note87 {get;set;}
    public String? Note88 {get;set;}
    public String? Note89 {get;set;}
    public String? Note90 {get;set;}
    public String? Note91 {get;set;}
    public String? Note92 {get;set;}
    public String? Note93 {get;set;}
    public String? Note94 {get;set;}
    public String? Note95 {get;set;}
    public String? Note96 {get;set;}
    public String? Note97 {get;set;}
    public String? Note98 {get;set;}
    public String? Note99 {get;set;}
}