namespace EntitySQLArk;

[PrimaryKey("ID")]
public partial class Tag : ModelBase
{
    public override Guid? ID {get;set;}

    public String? Tag0  {get;set;}
    public String? Tag1  {get;set;}
    public String? Tag2  {get;set;}
    public String? Tag3  {get;set;}
    public String? Tag4  {get;set;}
    public String? Tag5  {get;set;}
    public String? Tag6  {get;set;}
    public String? Tag7  {get;set;}
    public String? Tag8  {get;set;}
    public String? Tag9  {get;set;}
    public String? Tag10 {get;set;}
    public String? Tag11 {get;set;}
    public String? Tag12 {get;set;}
    public String? Tag13 {get;set;}
    public String? Tag14 {get;set;}
    public String? Tag15 {get;set;}
    public String? Tag16 {get;set;}
    public String? Tag17 {get;set;}
    public String? Tag18 {get;set;}
    public String? Tag19 {get;set;}
    public String? Tag20 {get;set;}
    public String? Tag21 {get;set;}
    public String? Tag22 {get;set;}
    public String? Tag23 {get;set;}
    public String? Tag24 {get;set;}
    public String? Tag25 {get;set;}
    public String? Tag26 {get;set;}
    public String? Tag27 {get;set;}
    public String? Tag28 {get;set;}
    public String? Tag29 {get;set;}
    public String? Tag30 {get;set;}
    public String? Tag31 {get;set;}
    public String? Tag32 {get;set;}
    public String? Tag33 {get;set;}
    public String? Tag34 {get;set;}
    public String? Tag35 {get;set;}
    public String? Tag36 {get;set;}
    public String? Tag37 {get;set;}
    public String? Tag38 {get;set;}
    public String? Tag39 {get;set;}
    public String? Tag40 {get;set;}
    public String? Tag41 {get;set;}
    public String? Tag42 {get;set;}
    public String? Tag43 {get;set;}
    public String? Tag44 {get;set;}
    public String? Tag45 {get;set;}
    public String? Tag46 {get;set;}
    public String? Tag47 {get;set;}
    public String? Tag48 {get;set;}
    public String? Tag49 {get;set;}
    public String? Tag50 {get;set;}
    public String? Tag51 {get;set;}
    public String? Tag52 {get;set;}
    public String? Tag53 {get;set;}
    public String? Tag54 {get;set;}
    public String? Tag55 {get;set;}
    public String? Tag56 {get;set;}
    public String? Tag57 {get;set;}
    public String? Tag58 {get;set;}
    public String? Tag59 {get;set;}
    public String? Tag60 {get;set;}
    public String? Tag61 {get;set;}
    public String? Tag62 {get;set;}
    public String? Tag63 {get;set;}
    public String? Tag64 {get;set;}
    public String? Tag65 {get;set;}
    public String? Tag66 {get;set;}
    public String? Tag67 {get;set;}
    public String? Tag68 {get;set;}
    public String? Tag69 {get;set;}
    public String? Tag70 {get;set;}
    public String? Tag71 {get;set;}
    public String? Tag72 {get;set;}
    public String? Tag73 {get;set;}
    public String? Tag74 {get;set;}
    public String? Tag75 {get;set;}
    public String? Tag76 {get;set;}
    public String? Tag77 {get;set;}
    public String? Tag78 {get;set;}
    public String? Tag79 {get;set;}
    public String? Tag80 {get;set;}
    public String? Tag81 {get;set;}
    public String? Tag82 {get;set;}
    public String? Tag83 {get;set;}
    public String? Tag84 {get;set;}
    public String? Tag85 {get;set;}
    public String? Tag86 {get;set;}
    public String? Tag87 {get;set;}
    public String? Tag88 {get;set;}
    public String? Tag89 {get;set;}
    public String? Tag90 {get;set;}
    public String? Tag91 {get;set;}
    public String? Tag92 {get;set;}
    public String? Tag93 {get;set;}
    public String? Tag94 {get;set;}
    public String? Tag95 {get;set;}
    public String? Tag96 {get;set;}
    public String? Tag97 {get;set;}
    public String? Tag98 {get;set;}
    public String? Tag99 {get;set;}
}