global using System;
global using Serilog;
global using System.IO;
global using System.Linq;
global using Serilog.Core;
global using Azure.Storage;
global using OpenTelemetry;
global using Serilog.Events;
global using System.Threading;
global using System.Diagnostics;
global using Azure.Storage.Blobs;
global using OpenTelemetry.Trace;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Exporter;
global using System.Threading.Tasks;
global using OpenTelemetry.Resources;
global using static System.Environment;
global using Azure.Storage.Blobs.Models;
global using System.Collections.Generic;
global using System.Diagnostics.Tracing;
global using Serilog.Sinks.OpenTelemetry;
global using Microsoft.ServiceFabric.Actors;
global using System.Runtime.CompilerServices;
global using static KusDepot.Data.BlobStrings;
global using static KusDepot.Data.BlobSettings;
global using Microsoft.Extensions.Configuration;
global using Microsoft.ServiceFabric.Actors.Runtime;
global using static System.Globalization.CultureInfo;
global using DiagnosticActivity = System.Diagnostics.Activity;